In [77]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([ [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])

y = np.array([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l1error = y - l1
    l1_delta = l1error * nonlin(l1,True)

      
print ("Output After Training:")
print (l1)


Output After Training:
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]


In [68]:
nonlin(1)

0.7310585786300049

In [64]:
nonlin(50)

1.0

In [22]:
nonlin(888)

1.0

In [23]:
np.exp(-1)

0.36787944117144233

In [10]:
x

NameError: name 'x' is not defined

In [11]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [13]:
np.random.seed(1)

In [14]:
z = np.random.seed(1)
print z

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-14-7f71f2c41990>, line 2)

In [15]:
print ("z")

z


In [16]:
print(z)

NameError: name 'z' is not defined

In [17]:
z = np.random.seed(1)
print(z)

None


In [73]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)
print(y)

Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]
[[0]
 [0]
 [1]
 [1]]
